version: '2'

services:

  zookeeper:
    image: java:8
    volumes:
      - ./kafka:/kafka
      - ./zookeeper.properties:/kafka/config/zookeeper.properties
    working_dir: /kafka
    command:
      - bin/zookeeper-server-start.sh
      - config/zookeeper.properties
    # ports:
    #   - 2181:2181

  kafka-broker-0:
    image: java:8
    volumes:
      - ./kafka:/kafka
      - ./server.properties:/kafka/config/server.properties
    working_dir: /kafka
    command:
      - bin/kafka-server-start.sh
      - config/server.properties
    ports:
      - 9092:9092

  # kafka-broker-1:
  #   image: java:8
  #   volumes:
  #     - ./kafka:/kafka
  #     - ./server.1.properties:/kafka/config/server.properties
  #   working_dir: /kafka
  #   command:
  #     - bin/kafka-server-start.sh
  #     - config/server.properties
  #   # ports:
  #   #   - 9093:9093

  # kafka-broker-2:
  #   image: java:8
  #   volumes:
  #     - ./kafka:/kafka
  #     - ./server.2.properties:/kafka/config/server.properties
  #   working_dir: /kafka
  #   command:
  #     - bin/kafka-server-start.sh
  #     - config/server.properties
  #   # ports:
  #   #   - 9094:9094

  producer:
    image: node:6
    volumes:
      - ./apps:/app
    working_dir: /app
    command: /app/start-producer.sh
    # ports:
    #   - 3000:3000


  consumer:
    image: node:6
    volumes:
      - ./apps:/app
    working_dir: /app
    command: /app/start-consumer.sh

  kafka-client:
    image: java:8
    volumes:
      - ./kafka:/kafka
    working_dir: /kafka/bin
    command:
      - sleep
      - infinity

  # traefik:
  #   image: emilevauge/traefik
  #   volumes:
  #     - ./traefik.toml:/traefik.toml
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8080:8080
  #     - 80:80