version: '2'

services:
  zookeeper:
    image: java:8
    volumes:
      - ./kafka:/kafka
      - ./zookeeper.properties:/kafka/config/zookeeper.properties
    working_dir: /kafka
    command:
      - bin/zookeeper-server-start.sh
      - config/zookeeper.properties

  kafka-broker-1:
    image: java:8
    volumes:
      - ./kafka:/kafka
      - ./server.properties:/kafka/config/server.properties
    working_dir: /kafka
    command:
      - bin/kafka-server-start.sh
      - config/server.properties

  kafka-client:
    image: java:8
    volumes:
      - ./kafka:/kafka
    working_dir: /kafka/bin
    command:
      - sleep
      - infinity
  
        